import {VersionDetailsReader} from '../../src/modules/catalogue/application/version-details.reader';
import {InMemoryCatalogueRepository} from '../../src/modules/catalogue/infrastructure/in-memory-catalogue.repository';
import {ProductVersion} from '../../src/modules/catalogue/domain/product-version';
describe('AC-M07-07 exact catalogue import match',()=>{
 let repo:InMemoryCatalogueRepository;let reader:VersionDetailsReader;
 beforeEach(async()=>{repo=new InMemoryCatalogueRepository();reader=new VersionDetailsReader(repo);await repo.saveInsurer({id:'ins',name:'Star Health',irdaiRegNo:'123',lines:['HEALTH'],active:true});await repo.saveProduct({id:'prod',insurerId:'ins',line:'HEALTH',name:'Assure',category:'HEALTH_INDIVIDUAL'});await repo.saveVersion(ProductVersion.restore({id:'v1',productId:'prod',insurerId:'ins',line:'HEALTH',uin:'ABC123',wordingVersion:'1',posEligible:false,channels:['IMF'],effectiveFrom:'2026-01-01',effectiveTo:'2026-12-31',status:'active',quoteRequirements:[],keyFacts:[{label:'survivalBenefitYears',value:'1,3'}]}));});
 it('matches exact normalized names and inclusive dates, preserving product facts',async()=>{expect(await reader.findProduct(' star  health ','ASSURE','2026-12-31')).toMatchObject({versionId:'v1',category:'HEALTH_INDIVIDUAL',keyFacts:[{label:'survivalBenefitYears',value:'1,3'}]});expect(await reader.findProduct('Star','Assure','2026-10-03')).toBeUndefined();expect(await reader.findProduct('Star Health','Assure','2027-01-01')).toBeUndefined();});
 it('returns no match for inactive insurer or ambiguous active versions',async()=>{const v=await repo.getVersion('v1');if(!v)throw new Error('missing fixture');await repo.saveVersion(ProductVersion.restore({...v.props,id:'v2'}));expect(await reader.findProduct('Star Health','Assure','2026-10-03')).toBeUndefined();await repo.saveInsurer({id:'ins',name:'Star Health',irdaiRegNo:'123',lines:['HEALTH'],active:false});expect(await reader.findProduct('Star Health','Assure','2026-10-03')).toBeUndefined();});
});
