const labels: Record<string, [string, string]> = {
  referrer_confirmed: ['Referrer link confirmed', 'संदर्भदाता लिंक की पुष्टि हुई'],
  custom_field: ['Custom field', 'कस्टम फ़ील्ड'], extra_field: ['Additional field', 'अतिरिक्त फ़ील्ड'], policy_preview: ['Policy preview', 'पॉलिसी पूर्वावलोकन'], refresh_progress: ['Refresh import progress', 'आयात प्रगति ताज़ा करें'],
  permission_denied: ['You do not have permission for this action.', 'इस कार्रवाई की अनुमति नहीं है।'], reference: ['Reference', 'संदर्भ'], calendar_days: ['Calendar days', 'कैलेंडर दिन'],
  dues_title: ['Premium dues and renewals', 'प्रीमियम देय और नवीनीकरण'], import_title: ['Import book', 'पॉलिसी आयात'], policies: ['Held policies', 'मौजूदा पॉलिसियाँ'], details: ['Policy details', 'पॉलिसी विवरण'],
  as_of: ['As of', 'जानकारी की तारीख'], confidence: ['Confidence', 'विश्वास स्तर'], source_disclaimer: ['Based on recorded information; confirm current status with the insurer.', 'दर्ज जानकारी पर आधारित; बीमाकर्ता से वर्तमान स्थिति की पुष्टि करें।'],
  mark_paid: ['Mark paid', 'भुगतान दर्ज करें'], paid_on: ['Paid on', 'भुगतान तारीख'], month: ['Month', 'महीना'], line: ['Insurance line', 'बीमा प्रकार'], all: ['All', 'सभी'], language: ['Switch language', 'भाषा बदलें'], no_dues: ['No dues for this day.', 'इस दिन कोई देय नहीं।'], grace_end: ['Grace ends', 'अनुग्रह अवधि समाप्त'], reminder: ['WhatsApp reminder', 'व्हाट्सऐप अनुस्मारक'], reminder_later: ['Reminders will be available with messaging.', 'संदेश सुविधा के साथ अनुस्मारक उपलब्ध होंगे।'],
  no_policies: ['No policies recorded.', 'कोई पॉलिसी दर्ज नहीं।'], commercials: ['Booking and premium', 'बुकिंग और प्रीमियम'], risk: ['Cover and risk details', 'कवर और जोखिम विवरण'], registration: ['Registration number', 'पंजीकरण संख्या'], schedule: ['Premium schedule', 'प्रीमियम अनुसूची'], no_schedule: ['No further installments.', 'आगे कोई किस्त नहीं।'],
  servicing_title: ['Servicing tracker', 'सेवा अनुरोध ट्रैकर'], no_requests: ['No open follow-ups.', 'कोई लंबित फॉलो-अप नहीं।'], followup_before: ['Follow-ups through', 'इस तारीख तक फॉलो-अप'], followup: ['Follow-up date', 'फॉलो-अप तारीख'], no_followup: ['No follow-up date', 'फॉलो-अप तारीख नहीं'], insurer_ref: ['Insurer reference', 'बीमाकर्ता संदर्भ'], portal: ['Insurer portal', 'बीमाकर्ता पोर्टल'], note: ['Note', 'नोट'], add_note: ['Add note', 'नोट जोड़ें'], new_request: ['Create servicing request', 'सेवा अनुरोध बनाएँ'], request_kind: ['Request type', 'अनुरोध प्रकार'],
  upload: ['Upload CSV', 'CSV अपलोड'], mapping: ['Review column mapping', 'कॉलम मैपिंग समीक्षा'], mapping_help: ['Confirm each column against the preview before validation.', 'सत्यापन से पहले पूर्वावलोकन में प्रत्येक कॉलम की पुष्टि करें।'], canonical: ['Policy field', 'पॉलिसी फ़ील्ड'], csv_header: ['CSV column', 'CSV कॉलम'], preview: ['First row preview', 'पहली पंक्ति पूर्वावलोकन'], map_column: ['Map column', 'कॉलम मैप करें'], ignore: ['Do not map', 'मैप न करें'], extra_key: ['Custom or risk field key', 'कस्टम या जोखिम फ़ील्ड कुंजी'], add_column: ['Add field mapping', 'फ़ील्ड मैपिंग जोड़ें'], confirm_mapping: ['Confirm mapping and validate', 'मैपिंग पुष्टि और सत्यापन'], review: ['Review rows', 'पंक्तियों की समीक्षा'], result: ['Import result', 'आयात परिणाम'], format: ['Import format', 'आयात प्रारूप'], csv_file: ['CSV file', 'CSV फ़ाइल'], invalid_csv: ['Use a valid CSV with headers, consistent columns and 1–5000 rows.', 'शीर्षक, समान कॉलम और 1–5000 पंक्तियों वाला वैध CSV चुनें।'], summary: ['{total} rows · {problems} problems · {duplicates} duplicates · {updates} updates', '{total} पंक्तियाँ · {problems} समस्याएँ · {duplicates} डुप्लिकेट · {updates} अपडेट'],
  review_filter: ['Review filter', 'समीक्षा फ़िल्टर'], row: ['Row', 'पंक्ति'], review_result: ['Match', 'मिलान'], problems: ['Validation reasons', 'सत्यापन कारण'], decision: ['Row decision', 'पंक्ति निर्णय'], referrer: ['Referrer confirmation', 'संदर्भदाता पुष्टि'], choose: ['Choose decision', 'निर्णय चुनें'], confirm_referrer: ['Confirm referrer', 'संदर्भदाता पुष्टि करें'], name_only: ['Without confirmation, keep the name only.', 'पुष्टि के बिना केवल नाम रखें।'], no_review_rows: ['No rows in this filter.', 'इस फ़िल्टर में कोई पंक्ति नहीं।'], commit: ['Commit reviewed rows', 'समीक्षित पंक्तियाँ आयात करें'], already_committed: ['This file was already committed.', 'इस फ़ाइल का आयात पहले हो चुका है।'], imported: ['Imported', 'आयातित'], updated: ['Updated', 'अपडेट'], skipped: ['Skipped', 'छोड़ा गया'], parties_created: ['Customers created', 'नए ग्राहक'], parties_linked: ['Customers linked', 'जुड़े ग्राहक'], rerun: ['Re-running the same file skips imported rows.', 'इसी फ़ाइल को दोबारा चलाने पर आयातित पंक्तियाँ छोड़ दी जाती हैं।'], import_another: ['Import another file', 'अन्य फ़ाइल आयात करें'],
};
const enums: Record<string, [string, string]> = {
  SAVINGS: ['Savings', 'बचत'], STANDARD_HEALTH: ['Standard health', 'मानक स्वास्थ्य'], HOME: ['Home', 'घर'], COMMERCIAL: ['Commercial', 'वाणिज्यिक'], POSP: ['POSP', 'पीओएसपी'], DIGITAL: ['Digital', 'डिजिटल'], PETROL: ['Petrol', 'पेट्रोल'], DIESEL: ['Diesel', 'डीजल'], CNG: ['CNG', 'सीएनजी'], LPG: ['LPG', 'एलपीजी'], ELECTRIC: ['Electric', 'इलेक्ट्रिक'], HYBRID: ['Hybrid', 'हाइब्रिड'], SELF: ['Self', 'स्वयं'], SPOUSE: ['Spouse', 'जीवनसाथी'], SON: ['Son', 'पुत्र'], DAUGHTER: ['Daughter', 'पुत्री'], FATHER: ['Father', 'पिता'], MOTHER: ['Mother', 'माता'], FATHER_IN_LAW: ['Father in law', 'ससुर'], MOTHER_IN_LAW: ['Mother in law', 'सास'],
  IMPORT: ['Imported', 'आयातित'], AI_EXTRACTED: ['AI extracted', 'AI से निकाला गया'], MANUAL: ['Manually recorded', 'मैन्युअल दर्ज'], PLATFORM_SALE: ['Platform sale', 'प्लेटफ़ॉर्म बिक्री'], HIGH: ['High', 'उच्च'], MEDIUM: ['Medium', 'मध्यम'], LOW: ['Low', 'कम'], LIFE: ['Life', 'जीवन'], HEALTH: ['Health', 'स्वास्थ्य'], GENERAL: ['General', 'सामान्य'],
  IN_FORCE: ['In force', 'सक्रिय'], GRACE: ['In grace', 'अनुग्रह अवधि'], LAPSED: ['Lapsed', 'व्यपगत'], PAID_UP: ['Paid up', 'पूर्ण भुगतान'], MATURED: ['Matured', 'परिपक्व'], SURRENDERED: ['Surrendered', 'समर्पित'], CLAIMED: ['Claimed', 'दावा किया'], EXPIRED: ['Expired', 'समाप्त'], CANCELLED: ['Cancelled', 'रद्द'], UPCOMING: ['Upcoming', 'आगामी'], DUE_TODAY: ['Due today', 'आज देय'], IN_GRACE: ['In grace', 'अनुग्रह अवधि'], REVIVABLE: ['Revivable', 'पुनर्जीवन योग्य'], RENEWAL_DUE: ['Renewal due', 'नवीनीकरण देय'], PAID: ['Paid', 'भुगतान हुआ'],
  ADDRESS_CHANGE: ['Address change', 'पता परिवर्तन'], NOMINEE_CHANGE: ['Nominee change', 'नामित व्यक्ति परिवर्तन'], BANK_MANDATE: ['Bank mandate', 'बैंक निर्देश'], SURRENDER: ['Surrender', 'समर्पण'], LOAN: ['Loan', 'ऋण'], CLAIM: ['Claim', 'दावा'], DUPLICATE_POLICY: ['Duplicate policy', 'पॉलिसी की प्रतिलिपि'], OTHER: ['Other', 'अन्य'], OPEN: ['Open', 'खुला'], SUBMITTED_TO_INSURER: ['Submitted to insurer', 'बीमाकर्ता को प्रस्तुत'], AWAITING_CUSTOMER: ['Awaiting customer', 'ग्राहक की प्रतीक्षा'], RESOLVED: ['Resolved', 'समाधान हुआ'], REJECTED: ['Rejected', 'अस्वीकृत'],
  CSV_TEMPLATE: ['CSV template', 'CSV टेम्पलेट'], LIC_PORTAL: ['LIC portal export', 'LIC पोर्टल निर्यात'], GENERIC_PORTAL: ['Other insurer export', 'अन्य बीमाकर्ता निर्यात'], OFFICE_SALES_REGISTER: ['Office sales register', 'कार्यालय बिक्री रजिस्टर'], NEW: ['New policy', 'नई पॉलिसी'], DUPLICATE_IN_BOOK: ['Already in book', 'बुक में मौजूद'], DUPLICATE_IN_FILE: ['Duplicate in file', 'फ़ाइल में डुप्लिकेट'], UPDATE: ['Newer information', 'नई जानकारी'], FRESH: ['Fresh', 'नई'], RENEWAL: ['Renewal', 'नवीनीकरण'], PORTABILITY: ['Portability', 'पोर्टेबिलिटी'], ROLLOVER: ['Rollover', 'रोलओवर'], IN_HOUSE: ['In house', 'कार्यालय से'], REFERRAL: ['Referral', 'रेफरल'], WALK_IN: ['Walk in', 'सीधे आने वाला'], ONLINE: ['Online', 'ऑनलाइन'], CAMPAIGN: ['Campaign', 'अभियान'], MOTOR: ['Motor', 'मोटर'], HEALTH_INDIVIDUAL: ['Individual health', 'व्यक्तिगत स्वास्थ्य'], HEALTH_FLOATER: ['Family floater', 'परिवार फ्लोटर'], INDIVIDUAL: ['Individual', 'व्यक्तिगत'], FLOATER: ['Floater', 'फ्लोटर'], TERM: ['Term life', 'टर्म जीवन'], ENDOWMENT: ['Endowment', 'बंदोबस्ती'], ULIP: ['ULIP', 'यूलिप'], PENSION: ['Pension', 'पेंशन'], CHILD: ['Child plan', 'बाल योजना'], TRAVEL: ['Travel', 'यात्रा'], PERSONAL_ACCIDENT: ['Personal accident', 'व्यक्तिगत दुर्घटना'], FIRE: ['Fire', 'अग्नि'],
};
const fields: Record<string, [string, string]> = {
  rowNo: ['Row number', 'पंक्ति संख्या'], members: ['Insured members', 'बीमित सदस्य'], relation: ['Relation', 'संबंध'], ageBand: ['Age band', 'आयु सीमा'], portabilityFrom: ['Previous continuous cover', 'पिछला निरंतर कवर'], continuousCoverSince: ['Covered since', 'कवर प्रारंभ'], variant: ['Variant', 'वेरिएंट'], fuel: ['Fuel', 'ईंधन'], ncbPercent: ['No claim bonus percentage', 'नो क्लेम बोनस प्रतिशत'], claimInPreviousYear: ['Claim in previous year', 'पिछले वर्ष दावा'], addOns: ['Add-ons', 'अतिरिक्त कवर'], ppt: ['Premium paying term', 'प्रीमियम भुगतान अवधि'], payoutOption: ['Payout option', 'भुगतान विकल्प'], riders: ['Riders', 'राइडर'],
  policyNumber: ['Policy number', 'पॉलिसी संख्या'], insurerName: ['Insurer', 'बीमाकर्ता'], productName: ['Product', 'उत्पाद'], holderName: ['Customer name', 'ग्राहक नाम'], mobile: ['Mobile', 'मोबाइल'], email: ['Email', 'ईमेल'], dob: ['Birth date', 'जन्म तारीख'], sumAssured: ['Sum assured / IDV', 'बीमित राशि / IDV'], premium: ['Premium', 'प्रीमियम'], mode: ['Premium mode', 'प्रीमियम आवृत्ति'], commencementDate: ['Risk start date', 'जोखिम प्रारंभ तारीख'], nextDueDate: ['Next due date', 'अगली देय तारीख'], maturityDate: ['Maturity date', 'परिपक्वता तारीख'], renewalDate: ['Renewal date', 'नवीनीकरण तारीख'], status: ['Status', 'स्थिति'], bookedOn: ['Booking date', 'बुकिंग तारीख'], expiryDate: ['Expiry date', 'समाप्ति तारीख'], category: ['Category', 'श्रेणी'], businessType: ['Business type', 'व्यवसाय प्रकार'], previousInsurerName: ['Previous insurer', 'पिछला बीमाकर्ता'], policyTerm: ['Policy term', 'पॉलिसी अवधि'], policyTermMonths: ['Term in months', 'महीनों में अवधि'], premiumNet: ['Net premium', 'शुद्ध प्रीमियम'], premiumGross: ['Gross premium', 'सकल प्रीमियम'], premiumTax: ['Premium tax', 'प्रीमियम कर'], odPremium: ['Own damage premium', 'स्वयं क्षति प्रीमियम'], tpPremium: ['Third party premium', 'तृतीय पक्ष प्रीमियम'], ncb: ['No claim bonus', 'नो क्लेम बोनस'], registrationNo: ['Registration number', 'पंजीकरण संख्या'], registrationYear: ['Registration year', 'पंजीकरण वर्ष'], familySizeOrModel: ['Family mix / model', 'परिवार मिश्रण / मॉडल'], bookingChannelCode: ['Booking channel', 'बुकिंग चैनल'], businessSource: ['Business source', 'व्यवसाय स्रोत'], referredByName: ['Referrer name', 'संदर्भदाता नाम'], referredBy: ['Referred by', 'संदर्भदाता'], remarks: ['Policy remarks', 'पॉलिसी टिप्पणी'], commissionAmount: ['Commission amount', 'कमीशन राशि'], commissionRatePct: ['Commission rate', 'कमीशन दर'], commissionRemarks: ['Commission remarks', 'कमीशन टिप्पणी'], invoiceNo: ['Invoice number', 'इनवॉइस संख्या'], line: ['Insurance line', 'बीमा प्रकार'], premiumNetPaise: ['Net premium', 'शुद्ध प्रीमियम'], premiumTaxPaise: ['Tax', 'कर'], premiumGrossPaise: ['Gross premium', 'सकल प्रीमियम'], odPremiumPaise: ['Own damage premium', 'स्वयं क्षति प्रीमियम'], tpPremiumPaise: ['Third party premium', 'तृतीय पक्ष प्रीमियम'], make: ['Make', 'निर्माता'], model: ['Model', 'मॉडल'], coverType: ['Cover type', 'कवर प्रकार'], memberMix: ['Family mix', 'परिवार मिश्रण'], adults: ['Adults', 'वयस्क'], children: ['Children', 'बच्चे'], ncbPct: ['No claim bonus percentage', 'नो क्लेम बोनस प्रतिशत'], portability: ['Portability', 'पोर्टेबिलिटी'],
};
const reasons: Record<string, [string, string]> = {
  invalid_amount: ['Invalid money amount', 'अमान्य राशि'], invalid_date: ['Invalid calendar date', 'अमान्य तारीख'], invalid_contact: ['Invalid contact', 'अमान्य संपर्क'], required: ['Required field missing', 'आवश्यक फ़ील्ड नहीं है'], invalid_mode: ['Unknown premium mode', 'अज्ञात प्रीमियम आवृत्ति'], premium_net_required: ['Net premium is required for commission', 'कमीशन के लिए शुद्ध प्रीमियम आवश्यक है'], premium_mismatch: ['Premium amounts do not match', 'प्रीमियम राशि मेल नहीं खाती'], invalid_category: ['Unknown product category', 'अज्ञात उत्पाद श्रेणी'], invalid_business_type: ['Unknown business type', 'अज्ञात व्यवसाय प्रकार'], unknown_business_source: ['Unknown source; classified as Other', 'अज्ञात स्रोत; अन्य वर्गीकृत'], invalid_term: ['Invalid policy term', 'अमान्य पॉलिसी अवधि'], invalid_rate: ['Invalid commission percentage', 'अमान्य कमीशन प्रतिशत'], invalid_record: ['Policy details need correction', 'पॉलिसी विवरण सुधारें'], invalid_risk_details: ['Risk details need correction', 'जोखिम विवरण सुधारें'], motor_premium_exceeds_net: ['Own damage and third party premiums exceed net premium', 'स्वयं क्षति और तृतीय पक्ष प्रीमियम शुद्ध प्रीमियम से अधिक हैं'], invalid_registration_number: ['Invalid registration number', 'अमान्य पंजीकरण संख्या'], registration_year_in_future: ['Registration year is in the future', 'पंजीकरण वर्ष भविष्य में है'], invalid_custom_fields: ['Custom fields need correction', 'कस्टम फ़ील्ड सुधारें'],
};
function build(index: 0 | 1): Record<string, string> {
  return Object.fromEntries([
    ...Object.entries(labels).map(([k, v]) => [`book.${k}`, v[index]]),
    ...Object.entries(enums).map(([k, v]) => [`book.enum.${k}`, v[index]]),
    ...Object.entries(fields).map(([k, v]) => [`book.field.${k}`, v[index]]),
    ...Object.entries(reasons).map(([k, v]) => [`book.reason.${k}`, v[index]]),
    ['book.filter.all', index === 0 ? 'All rows' : 'सभी पंक्तियाँ'], ['book.filter.problems', index === 0 ? 'Problems' : 'समस्याएँ'], ['book.filter.duplicates', index === 0 ? 'Duplicates' : 'डुप्लिकेट'],
    ['book.decision.IMPORT', index === 0 ? 'Import' : 'आयात'], ['book.decision.UPDATE', index === 0 ? 'Update' : 'अपडेट'], ['book.decision.SKIP', index === 0 ? 'Skip' : 'छोड़ें'],
  ]);
}
export const bookMessagesEn = build(0);
export const bookMessagesHi = build(1);
